# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Record

# Model Form Field configuration
form: $/ncarps/projects/models/record/fields.yaml

# Model Class name
modelClass: Ncarps\Projects\Models\Record

# Default redirect location
defaultRedirect: ncarps/projects/records

# Create page
create:
    title: backend::lang.form.create_title
    redirect: ncarps/projects/records/update/:id
    redirectClose: ncarps/projects/records

# Update page
update:
    title: backend::lang.form.update_title
    redirect: ncarps/projects/records
    redirectClose: ncarps/projects/records

# Preview page
preview:
    title: backend::lang.form.preview_title
