# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Project

# Model Form Field configuration
form: $/ncarps/projects/models/project/fields.yaml

# Model Class name
modelClass: Ncarps\Projects\Models\Project

# Default redirect location
defaultRedirect: ncarps/projects/projects

# Create page
create:
    title: backend::lang.form.create_title
    redirect: ncarps/projects/projects/update/:id
    redirectClose: ncarps/projects/projects

# Update page
update:
    title: backend::lang.form.update_title
    redirect: ncarps/projects/projects
    redirectClose: ncarps/projects/projects

# Preview page
preview:
    title: backend::lang.form.preview_title
